### PR TITLE
Add Teapot-ACL

### PR DESCRIPTION
**Pull request by radekbusa**

### CODE REVIEW

**Review by juliendelplanque — APPROVED** [review]
Nice contribution.

**Comment by radekbusa** [comment]
@juliendelplanque thank you. it looks like there is a problem with travis check status. please merge the pr. thank you :)

**Comment by SergeStinckwich** [comment]
Can we merge this?

**Comment by jecisc** [comment]
Sorry for the delay and thank you for the contribution :)

**Pull request merged**
